# Known Bugs Catalog

## Purpose

This file is the single source of truth for every bug-driven test in the `easyrice` codebase. Each entry pairs a failing (or passing-once-fixed) test with a citation to the spec it enforces, plus a short argument for why the test itself is correct. The catalog is generated by hand and verified mechanically against the test markers.

If a test references `BUG-NNN`, that ID **must** exist here. If a row exists here without a matching test marker, the catalog is stale.

## BUG-NNN Convention

Every entry follows this exact template. Copy it verbatim when adding a new entry:

```
## BUG-NNN — short title
**Status**: failing | passing | wont-fix
**Severity**: S1 | S2 | S3
**Package**: internal/<pkg>
**Test**: <path/to/test.go>:TestFunctionName
**Spec source**: <citation>
**Expected**: <intended behavior>
**Actual**: <current behavior>
**Repro**: <minimal commands or test seed>
**How we know test is correct**: <pointer or argument>
```

### Severity scale

- **S1**: data loss, corruption, or security boundary breach. Drop everything.
- **S2**: a documented feature is broken or returns wrong results, but no data is at risk.
- **S3**: UX wart, confusing error message, cosmetic drift.

### Status values

- **failing**: test exists and currently fails on `main`. The bug is real and unfixed.
- **passing**: bug has been fixed; test stays as a regression guard.
- **wont-fix**: documented behavior, kept as a pinned reminder. Explain why in **How we know test is correct**.

### How to add a new entry

1. Pick the next free `NNN` from the package's reserved block (see bottom of this file).
2. Copy the template above into the `## Catalog` section, keeping entries sorted by `NNN`.
3. Add the matching marker comment in your test file: `// BUG-NNN`.
4. Run the verification one-liner under `## Verification`. Test count and catalog count must match.
5. Commit the catalog entry and the test in the same commit.

## Catalog

## BUG-000 — Example — remove before completing Task 18
**Status**: failing
**Severity**: S3
**Package**: internal/example
**Test**: internal/example/example_test.go:TestPlaceholder
**Spec source**: `.omo/plans/better-tests.md` line 879 (Task 7 acceptance criteria require one example entry)
**Expected**: This placeholder entry is removed before the better-tests plan reaches Task 18.
**Actual**: Placeholder still present, demonstrating the template format.
**Repro**: No test exists; this entry is illustrative only.
**How we know test is correct**: N/A, this row is a format demonstration and is deleted once real entries land.

## Verification

```bash
# Check that every BUG-NNN in test files has a matching entry in this catalog:
TEST_COUNT=$(grep -rh 'BUG-[0-9]\{3\}' --include='*_test.go' | grep -oE 'BUG-[0-9]{3}' | sort -u | wc -l)
CATALOG_COUNT=$(grep -c '^## BUG-[0-9]\{3\}' .omo/known-bugs.md)
echo "tests=$TEST_COUNT catalog=$CATALOG_COUNT"
test "$TEST_COUNT" = "$CATALOG_COUNT"
```

Run this from the repo root. A non-zero exit means the catalog and test files have drifted; fix the mismatch before merging.

## NNN Numbering Block Reservations

NNN is a zero-padded 3-digit number (001, 002, ..., 199). Blocks are reserved per package so parallel tasks don't collide on IDs.

- 001-019: state
- 020-039: manifest
- 040-059: profile
- 060-079: installer (incl. concurrency)
- 080-099: updater
- 100-119: multi-remote
- 120-139: symlink/path
- 140-159: git
- 160-179: CLI/UX
- 180-199: E2E scenarios

When a block fills up, extend it in increments of 20 and update this section in the same PR.
